### ISSUE TITLE
HTTP 401 Unauthorized, {"message": "401: Unauthorized", "code": 0}

### ISSUE THREAD

**Issue by psyciknz** [kylegrantlucas/discord-smtp-server#2]
Getting an unauthorised.  

I tried the following docker compose:
```
services:
  discord-smtp:
    container_name: discord-smtp
    image: kylegrantlucas/discord-smtp-server
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SMTP_USERNAME=username
      - SMTP_PASSWORD=password
    ports:
      - "2525:1025"
```

It starts, and if I (using thunderbird) set the account user as username and password as password I get the 401 Unauthorized.

I assume that's from th SMTP side.  If get the password wrong or set any of the other options thunderbird will tell me about it.

I also tried the sample telnet:
```
EHLO localhost
AUTH PLAIN
AHVzZXJuYW1lAHBhc3N3b3Jk
MAIL FROM:<test@test.com>
RCPT TO:<smtp@alert.karenplankton>
DATA
Hey
.
```

And got the same mesage.
```
discord-smtp    | 2022/12/02 01:48:58 HTTP 401 Unauthorized, {"message": "401: Unauthorized", "code": 0}
```
That's not from discord is it?  There's no mention of how and where to get the token from - which I got the authorization token using this method:  https://linuxhint.com/get-discord-token/#:~:text=Discord%20tokens%20act%20as%20an,creates%20a%20new%20Discord%20account.
